name: build

on: [push]

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'
      - run: java -cp java HelloWorldApp